# EX 9.1

In [1]:
import numpy
import random
from scipy.linalg import toeplitz
import scipy


r = numpy.random.randint(0, 10, (1, 500))
c = numpy.random.randint(0, 10, (500, 1))
B = toeplitz(c, r)
A = numpy.random.randint(0, 10, (200,500))

print('A :', A)
print('B :', B)

#A+A
print('A+A :',A + A)
#AB
print(numpy.dot(A,B))
#A(B − λI)
def fun1(A, B, tmp):
    return numpy.dot(A, B-tmp* numpy.ones(dtype=int, shape = B.shape))
print(fun1(A, B, 1))

A : [[0 3 7 ... 0 4 7]
 [0 9 6 ... 0 1 2]
 [0 6 9 ... 2 1 6]
 ...
 [5 9 9 ... 8 2 9]
 [7 8 6 ... 7 4 8]
 [6 2 7 ... 8 6 3]]
B : [[9 7 8 ... 5 6 1]
 [6 9 7 ... 0 5 6]
 [5 6 9 ... 6 0 5]
 ...
 [1 3 1 ... 9 7 8]
 [8 1 3 ... 6 9 7]
 [6 8 1 ... 5 6 9]]
A+A : [[ 0  6 14 ...  0  8 14]
 [ 0 18 12 ...  0  2  4]
 [ 0 12 18 ...  4  2 12]
 ...
 [10 18 18 ... 16  4 18]
 [14 16 12 ... 14  8 16]
 [12  4 14 ... 16 12  6]]
[[10160 10196 10356 ...  9846  9442  9536]
 [10185 10423 10361 ...  9827  9952 10163]
 [ 9872  9616  9913 ...  9593  9731  9748]
 ...
 [ 9886  9696  9614 ...  9556  9633  9354]
 [ 9814  9907 10127 ...  9596  9537 10204]
 [10253 10362 10361 ... 10339 10404 10401]]
[[7962 7998 8158 ... 7648 7244 7338]
 [7925 8163 8101 ... 7567 7692 7903]
 [7686 7430 7727 ... 7407 7545 7562]
 ...
 [7738 7548 7466 ... 7408 7485 7206]
 [7605 7698 7918 ... 7387 7328 7995]
 [7953 8062 8061 ... 8039 8104 8101]]


# EX 9.2 

In [2]:
b = numpy.random.randint(0, 10, 500)
print(b)
BI = numpy.mat(B).I

print(BI)
print('-----')
print(numpy.dot(b, BI))



[9 2 8 3 1 2 7 3 3 9 0 6 6 2 3 6 3 4 4 7 3 0 1 6 6 4 2 5 9 3 6 1 7 4 5 1 0
 1 4 7 9 9 2 4 1 4 7 6 7 5 1 1 4 5 8 7 2 7 8 4 4 5 9 6 6 9 7 0 4 2 4 1 1 1
 4 1 9 1 7 4 0 7 2 8 7 3 8 8 2 5 1 6 0 7 8 9 4 7 9 9 8 2 9 8 4 1 8 7 1 0 7
 8 4 3 3 9 2 1 0 7 4 8 2 9 6 0 2 4 6 1 7 5 1 0 8 4 4 7 3 1 4 7 7 9 8 1 3 3
 4 1 8 7 5 4 2 4 8 8 0 3 8 2 8 8 2 2 1 6 9 6 1 1 3 9 1 4 5 8 2 9 1 8 8 5 9
 1 5 5 7 3 5 4 0 6 4 4 1 4 4 3 1 4 0 7 3 0 9 6 7 6 3 5 1 1 1 8 5 7 2 4 0 1
 7 3 9 4 4 9 5 3 4 2 3 1 0 2 3 4 0 8 4 4 2 0 7 6 8 7 5 7 2 0 7 6 6 8 9 7 0
 0 5 1 7 9 3 2 8 6 7 8 0 2 7 5 9 4 0 5 0 8 9 5 0 4 1 2 2 3 0 9 6 4 3 2 3 6
 0 9 6 2 1 6 9 4 1 6 0 4 1 3 7 0 3 3 3 3 9 0 8 4 8 6 3 8 7 5 0 1 3 4 7 8 3
 1 1 5 4 3 8 5 6 1 8 9 3 4 5 1 9 1 8 0 6 6 7 9 5 5 5 1 1 1 6 3 0 1 5 6 8 5
 9 1 7 5 1 9 0 9 7 0 7 1 9 2 5 2 1 2 9 3 1 2 6 5 8 1 6 8 6 5 6 4 4 3 4 2 2
 2 7 6 5 0 6 3 2 1 9 0 6 8 2 0 4 7 5 5 8 5 2 3 6 3 5 3 7 9 4 3 1 9 3 7 6 1
 8 4 0 4 1 5 6 4 2 5 8 0 6 1 6 8 0 6 6 1 1 0 0 5 8 0 8 4 8 5 1 0 1 0 5 2 8
 3 9 5 7 4 5 6 3 3 0 5 4 

# EX 9.3

In [3]:
print(numpy.linalg.norm(A))
print(numpy.linalg.norm(B, ord=numpy.inf))

print('smallest:', numpy.linalg.norm(B, ord=-2))
print('largest:', numpy.linalg.norm(B, ord=2))

1690.2899159611643
2314.0
smallest: 0.6110282536168464
largest: 2248.9577135769705


#  EX9.4

In [ ]:
n = input('input n: ')
n = int(n)
Z = numpy.random.randint(0, 10, (n, n))
def power_iteration(Z):
    time = 0
    b = numpy.random.randint(Z.shape[1])
    while True:
        b1 = numpy.dot(Z, b)
        norm = numpy.linalg.norm(b1)
        b = b1/norm
        norm2 = numpy.linalg.norm(b)
        if abs(norm - norm2)/norm <= 0.00001:
            break
        time += 1
    print('iteration time :', time)
    print(b)

power_iteration(Z)

# EX 9.5

In [ ]:
n = int(input('input n: '))
C = []
p = float(input('input P: '))
for i in range(0, n):
    tmp = []
    for j in range(0, n):
        if random.uniform(0, 1) > p:
            tmp.append(0)
        else:
            tmp.append(1)
    C.append(tmp)

U, sigma, VT = scipy.linalg.svd(C)
print(sigma)

# EX 9.6

In [ ]:
AA = numpy.random.randint(0, 10, 10)
print(AA)
print(AA,len(AA))

z = int(input('input z: '))
BB = [abs(i - z) for i in AA]
print(BB)
print('num', AA[numpy.argmin(B)])